#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=dual_50agents
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=Slurm_outputs/dual_50agents.out
# 1. Load system modules
module purge
module load 2024
module load Anaconda3/2024.06-1
module load CUDA/12.6.0
module load cuDNN/9.5.0.50-CUDA-12.6.0

source activate intervention

# Change to project root directory
cd /home/scur0073/Pre-Strategy-Intervention

pip install -e .[algs]
export WANDB_NAME="dual VDN MPE (50 agents)"


python baselines/QLearning/vdn_pre.py +alg=vdn \
  ++alg.ENTITY="lev-h-university-of-amsterdam" \
  ++alg.PROJECT="MPE_more_agents" \
  ++alg.WANDB_MODE="online" \
  ++alg.ENV_KWARGS.num_agents=50 \
  ++alg.ENV_KWARGS.num_landmarks=50 \
  ++alg.ENV_KWARGS.dual_target=True